### PR TITLE
Grow single column during `grow`

### LINKED ISSUE #26: Allocation beyond single column width
We're using `BucketedAtlasAllocator` to create an initial atlas size of 256x256. If we run into a glyph that's wider than 256, we attempt to grow the atlas to 512x512 then find an allocation for that glyph.

When we try to grow the atlas, `grow` keeps the original column width of 256 and instead updates `num_columns` to 2 (512/256): https://github.com/nical/etagere/blob/95d6f376fa85a265fd4493a0bf371777196b33b4/src/bucketed.rs#L154

When we try to find the allocation, this fails at https://github.com/nical/etagere/blob/95d6f376fa85a265fd4493a0bf371777196b33b4/src/bucketed.rs#L172

because `requested_size` (>256) is greater than `column_width` (still 256).

We could set a higher initial atlas size as a temporary work around, but I was wondering what the best path forward might be. Should allocations be able to span multiple columns somehow, or should we try to resize the column width while keeping existing allocations in place?

### PR DESCRIPTION
**Pull request by grovesNL**
Fixes #26

### CODE REVIEW

**Comment by nical** [comment]
Thanks!

**Comment by hecrj** [comment]
This seems to alter the position of the existing allocations or break the allocator somehow. `iced` relies on `glyphon`, which in turn relies on `grow`, and we have broken text rendering when the internal glyph atlas is resized (https://github.com/iced-rs/iced/issues/2132):

image

I confirmed the issue isn't there with `0.2.8`. Could we yank the latest release for the time being?

**Comment by nical** [comment]
Alright, thanks for reporting this, I yanked `0.2.9`. I'll try to make a test case from the tour example hopefully soon.

**Comment by grovesNL** [comment]
Sorry about that. I'll try to reproduce it with a smaller test case too.

**Comment by hecrj** [comment]
No worries! I can try to figure it out as well once I get the chance,
although I'm not very familiar with the algorithm.

From a quick glance, can `add_bucket` really be used for filling the
available space in shelves out of order? It seems the buckets are in a
specific linked sequence. Doesn't the last bucket of each shelf need to be
updated too?

**Comment by grovesNL** [comment]
I'm not totally sure, but it seems reasonable because that's how buckets are allocated initially too.

It looks like we should change the initial `bucket_next` to something like this:
```rust
let mut bucket_next = self.shelves[shelf_index].first_bucket;
```
(instead of `bucket_next = last_bucket_on_shelf`)

That change fixes `tour` but seems to regress `grow_horizontally`, so I need to look into it some more.

**Comment by grovesNL** [comment]
It looks like `grow_horizontally` wants to make an allocation that won't fit onto the empty shelves after coalescing, so adding buckets wouldn't work in general here. We'd need to add columns or shelves (by growing in height), or a more complicated hybrid that can split a column into its own set of shelves (described in #26).

Before growing:
before

Previous behavior after growing: a new column that is able to handle the allocation (allocation succeeded and displayed on the right)
after

New behavior after growing: new buckets are added but they're not big enough to handle the allocation
after

@hecrj does it sound ok to require growing height in this case? glyphon would grow in both dimensions by default

**Pull request merged**
